# Generated by Django 4.2.2 on 2024-05-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="item", name="timestamp",),
    ]
