# Generated by Django 4.2.2 on 2024-05-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_api", "0002_remove_item_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="stock_availibility",
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
